### ISSUE TITLE
Popup or treeview with checklist of things to do for that task

### ISSUE THREAD

**Issue by slideclimb** [deltadak/plep#37]
### Moved to #71 (PR)

**IDEAS**
- SO suggestion for [drag and drop](http://stackoverflow.com/a/23686466/6629569) in a tree view. Seems to be difficult...

**TODO**
- [x] loading the whole gridpane takes longer than old plep
- [x] update view
  - [x] showing label
  - [x] showing colour
- [x] update database (when editing a cell)
  - [x] when editing text
  - [x] when changing label 
- [x] modify database with `done` option (true or false)
  - **loading the first time takes really long (and errors), after that it works fine...**
    -> now it always works?
  - [x] update database when changing done status
- [x] drag and drop
- [x] add table in database for subtasks
  - [x] get subtasks from database to update view
  - [x] update database when adding new subtask
- [x] add empty items by default, so we can edit them
- [x] be able to add children to task (context menu?)
